# Dict with the description of each features to show in the app
FEATURE_AUG = {
    "rank": "Rang de la commune classé par ",
    "pct": "Taux de variation annuel ",
}

FEATURES_MAP = {
    "pop": "population totale",
    "popf": "population féminine",
    "poph": "population masculine",
    "pop014": "population de 0-14 ans",
    "pop1539": "population de 15-39 ans",
    "pop4059": "population de 40-59 ans",
    "pop60p": "population de 60 ans et plus",
    "popf014": "population féminine de 0-14 ans",
    "popf1539": "population féminine de 15-39 ans",
    "popf4059": "population féminine de 40-59 ans",
    "popf60p": "population féminine de 60 ans et plus",
    "popm014": "population masculine de 0-14 ans",
    "popm1539": "population masculine de 15-39 ans",
    "popm4059": "population masculine de 40-59 ans",
    "popm60p": "population masculine de 60 ans et plus",
    "prop014": "proportion de 0-14 ans (%)",
    "prop1539": "proportion de 15-39 ans (%)",
    "prop4059": "proportion de 40-59 ans (%)",
    "prop60p": "proportion de 60 ans et plus (%)",
    "propf": "proportion de femmes (%)",
    "propf014": "proportion de femmes de 0-14 ans (%)",
    "propf1539": "proportion de femmes de 15-39 ans (%)",
    "propf4059": "proportion de femmes de 40-59 ans (%)",
    "propf60p": "proportion de femmes de 60 ans et plus (%)",
    "propf014": "proportion de femmes de 0-14 ans (%)",
    "propf1559": "proportion de femmes de 15-59 ans (%)",
    "age": "âge moyen",
    "agef": "âge moyen des femmes",
    "ageh": "âge moyen des hommes",
    "perpropf": "percentile de la proportion de femmes",
    "perage": "percentile de l'âge moyen",
    "perprop014": "percentile de la proportion de 0-14 ans",
    "perprop60p": "percentile de la proportion de 60 ans et plus",
    # ========== ÉDUCATION ET DIPLÔMES ==========
    "nodip": "nombre de personnes sans diplôme (25+ ans)",
    "nodipf": "nombre de femmes sans diplôme (25+ ans)",
    "nodiph": "nombre d'hommes sans diplôme (25+ ans)",
    "bac": "nombre de bacheliers (25+ ans)",
    "bacf": "nombre de femmes bachelières (25+ ans)",
    "bach": "nombre d'hommes bacheliers (25+ ans)",
    "sup": "nombre de diplômés du supérieur (25+ ans)",
    "supf": "nombre de femmes diplômées du supérieur (25+ ans)",
    "suph": "nombre d'hommes diplômés du supérieur (25+ ans)",
    "pbac": "proportion de bacheliers (%)",
    "psup": "proportion de diplômés du supérieur (%)",
    "perbac": "percentile de la proportion de bacheliers",
    "persup": "percentile de la proportion de diplômés du supérieur",
    "alpha": "nombre de personnes alphabétisées (20+ ans)",
    "palpha": "proportion de personnes alphabétisées (%)",
    "peralpha": "percentile de la proportion d'alphabétisés",
    # ========== EMPLOI ET CSP ==========
    "pact": "population active (25-54 ans)",
    "agri": "nombre d'agriculteurs (25-54 ans)",
    "indp": "nombre d'indépendants (25-54 ans)",
    "cadr": "nombre de cadres (25-54 ans)",
    "pint": "nombre de professions intermédiaires (25-54 ans)",
    "empl": "nombre d'employés (25-54 ans)",
    "ouvr": "nombre d'ouvriers (25-54 ans)",
    "chom": "nombre de chômeurs (25-54 ans)",
    "pagri": "proportion d'agriculteurs (%)",
    "pindp": "proportion d'indépendants (%)",
    "pcadr": "proportion de cadres (%)",
    "ppint": "proportion de professions intermédiaires (%)",
    "pempl": "proportion d'employés (%)",
    "pouvr": "proportion d'ouvriers (%)",
    "pchom": "proportion de chômeurs (%)",
    "aind": "nombre d'agriculteurs et indépendants (25-54 ans)",
    "aica": "nombre d'agriculteurs, indépendants et cadres (25-54 ans)",
    "ouem": "nombre d'ouvriers et employés (25-54 ans)",
    "capi": "nombre de cadres et professions intermédiaires (25-54 ans)",
    "paind": "proportion d'agriculteurs et indépendants (%)",
    "paica": "proportion d'agriculteurs, indépendants et cadres (%)",
    "pouem": "proportion d'ouvriers et employés (%)",
    "pcapi": "proportion de cadres et professions intermédiaires (%)",
    "peragri": "percentile de la proportion d'agriculteurs",
    "perindp": "percentile de la proportion d'indépendants",
    "percadr": "percentile de la proportion de cadres",
    "perpint": "percentile de la proportion de professions intermédiaires",
    "perempl": "percentile de la proportion d'employés",
    "perouvr": "percentile de la proportion d'ouvriers",
    "perchom": "percentile de la proportion de chômeurs",
    # ========== NATIONALITÉS ET ORIGINES ==========
    "francais": "nombre de personnes de nationalité française",
    "etranger": "nombre de personnes de nationalité étrangère",
    "petranger": "proportion de personnes étrangères (%)",
    "peretr": "percentile de la proportion d'étrangers",
    "etranalg": "nombre de personnes de nationalité algérienne",
    "frarapat": "nombre de français rapatriés d'algérie",
    "pfrarapat": "proportion de rapatriés d'algérie (%)",
    "frannaiss": "nombre de français à la naissance",
    "frannatur": "nombre de français par naturalisation",
    "etraeuro": "nombre d'étrangers européens",
    "etraxeur": "nombre d'étrangers extra-européens",
    "immigre": "nombre d'immigrés (nés étrangers à l'étranger)",
    "pimmigre": "proportion d'immigrés (%)",
    "perimmigre": "percentile de la proportion d'immigrés",
    "immnatur": "nombre d'immigrés naturalisés",
    "pimmnatur": "proportion d'immigrés naturalisés (%)",
    "natur": "nombre de personnes naturalisées",
    "pnatur": "proportion de personnes naturalisées (%)",
    "pnaturfra": "proportion de naturalisés parmi les français (%)",
    # ========== REVENUS ET CAPITAL ==========
    "revratio": "revenu moyen par habitant (ratio national)",
    "revtot": "revenu total (fraction du total national)",
    "revmoy": "revenu moyen par habitant (en euros)",
    "revmoyfoy": "revenu moyen par foyer (en euros)",
    "revmoyadu": "revenu moyen par adulte (en euros)",
    "revratiofoy": "revenu moyen par foyer (ratio national)",
    "revratioadu": "revenu moyen par adulte (ratio national)",
    "perrev": "percentile du revenu moyen par habitant",
    "perrevfoy": "percentile du revenu moyen par foyer",
    "perrevadu": "percentile du revenu moyen par adulte",
    "nfoyer": "nombre de foyers fiscaux",
    "nadult": "nombre d'adultes (20+ ans)",
    "pibratio": "pib par habitant (ratio national)",
    "pibtot": "pib total (fraction du pib national)",
    "perpibratio": "percentile du pib par habitant",
    "capitalratio": "capital immobilier par habitant (ratio national)",
    "capitalimmo": "capital immobilier total (fraction du total national)",
    "percap": "percentile du capital immobilier par habitant",
    "prixbien": "prix moyen des logements (en euros)",
    "prixm2": "prix moyen au m² (en euros)",
    "prixm2ratio": "prix moyen au m² (ratio national)",
    "surfacH": "surface moyenne des logements (en m²)",
    "surfaceterrain": "surface moyenne du terrain (en m²)",
    "propappartement": "proportion d'appartements (%)",
    # ========== LOGEMENT ET PROPRIÉTÉ ==========
    "nlogement": "nombre total de logements",
    "npropri": "nombre de ménages propriétaires",
    "ppropri": "proportion de ménages propriétaires (%)",
    "perpropri": "percentile de la proportion de propriétaires",
    "nexploit": "nombre d'exploitations agricoles",
    "surface": "surface agricole totale (en hectares)",
    "psurface50p": "proportion de surfaces agricoles de +50 hectares (%)",
    "persur50p": "percentile de la proportion de surfaces de +50 hectares",
    # ========== FISCALITÉ ==========
    "basehabitationratio": "base d'habitation par habitant (ratio national)",
    "basefonciere_ratio": "base foncière par habitant (ratio national)",
    "baseimpotslocauxratio": "base des impôts locaux par habitant (ratio national)",
    "recettehabitationratio": "recette d'habitation par habitant (ratio national)",
    "recettefonciere_ratio": "recette foncière par habitant (ratio national)",
    "recetteimpotslocauxratio": "recette des impôts locaux par habitant (ratio national)",
    "tauxhabitationratio": "taux d'habitation communal (ratio national)",
    "tauxfoncierratio": "taux foncier communal (ratio national)",
    "tauximpotslocauxratio": "taux des impôts locaux (ratio national)",
    "recetteratio": "recette communale totale par habitant (ratio national)",
    # ========== ÉLECTIONS ==========
    # Participation générale
    "electeurs": "nombre d'électeurs (potentiels)",
    "inscrits": "nombre d'inscrits sur les listes électorales",
    "previouspvotepar": "taux de participation à l'élection précédente (du même type) (%)",
    "previouspreviouspvotepar": "taux de participation il y a deux élections (du même type) (%)",
    # Blocs politiques (G: Gauche, D: Droite, C: Centre, CG: Centre-Gauche, CD: Centre-Droit)
    "previouspvoteG": "taux de vote pour le bloc de gauche à l'élection précédente (%)",
    "previouspreviouspvoteG": "taux de vote pour le bloc de gauche il y a deux élections (%)",
    "previouspvoteD": "taux de vote pour le bloc de droite à l'élection précédente (%)",
    "previouspreviouspvoteD": "taux de vote pour le bloc de droite il y a deux élections (%)",
    "previouspvoteC": "taux de vote pour le bloc du centre à l'élection précédente (%)",
    "previouspreviouspvoteC": "taux de vote pour le bloc du centre il y a deux élections (%)",
    "previouspvoteCG": "taux de vote pour le bloc centre-gauche à l'élection précédente (%)",
    "previouspreviouspvoteCG": "taux de vote pour le bloc centre-gauche il y a deux élections (%)",
    "previouspvoteCD": "taux de vote pour le bloc centre-droit à l'élection précédente (%)",
    "previouspreviouspvoteCD": "taux de vote pour le bloc centre-droit il y a deux élections (%)",
    # ========== GÉOGRAPHIE ET AGGLOMÉRATIONS ==========
    "popagglo": "population de l'agglomération",
    "revratioagglo": "revenu moyen par habitant de l'agglomération (ratio national)",
    "capitalratioagglo": "capital immobilier par habitant de l'agglomération (ratio national)",
    "percommu": "percentile de la taille de la commune",
    "peragglo": "percentile de la taille de l'agglomération",
    "multicommune": "indicateur d'agglomération multi-communes (0-1)",
    "numcommune": "numéro de la commune dans l'agglomération",
    "codeagglo": "code de l'agglomération",
    "nomagglo": "nom de l'agglomération",
    "vbbm": "classification village-bourg-banlieue-métropole (1-4)",
    "vbbmpauvresriches": "classification village-bourg-banlieue-métropole par revenu (1-8)",
    # ========== SÉCURITÉ ==========
    "ncrimesdelits": "nombre total de crimes et délits",
    "nviolences": "nombre de violences contre les personnes",
    "ncambriolages": "nombre de cambriolages de logements",
    "nvolsvoitures": "nombre de vols de voitures",
    "nautresvols": "nombre d'autres vols",
    "pcrimesdelits": "nombre de crimes et délits pour 1000 habitants",
    "pviolences": "nombre de violences pour 1000 habitants",
    "pcambriolages": "nombre de cambriolages pour 1000 habitants",
    "pvolsvoitures": "nombre de vols de voitures pour 1000 habitants",
    "pautresvols": "nombre d'autres vols pour 1000 habitants",
    "percrimesdelits": "percentile du nombre de crimes et délits par habitant",
    # ========== SOCIAL ==========
    "rsa": "nombre d'allocataires du rsa",
    "isf": "nombre de contribuables à l'isf/ifi",
    # ========== GÉOLOCALISATION ==========
    "lat": "latitude",
    "long": "longitude",
    "dep": "code du département",
    "dep_num": "numéro du département",
    "nomdep": "nom du département",
    "reg": "code de la région",
    "nomreg": "nom de la région",
    "codecommune": "code de la commune",
    "nomcommune": "nom de la commune",
    "paris": "indicateur paris (0: hors paris, 1: arrondissements, 2: commune entière)",
    "plm": "indicateur paris-lyon-marseille (0: non plm, 1: arrondissements, 2: communes entières)",
    "cog": "code officiel géographique",
}
